/* Generated by Pyrex 0.9.5.1a on Mon Mar 10 22:54:45 2008 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "sys/types.h"
#include "errno.h"
#include "sys/param.h"
#include "unistd.h"
#include "sys/time.h"
#include "time.h"
#include "sys/times.h"
#include "stdlib.h"
#include "stdio.h"
#include "../graphfile/graphfile.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static void __Pyx_WriteUnraisable(char *name); /*proto*/

static PyObject *__Pyx_UnpackItem(PyObject *); /*proto*/
static int __Pyx_EndUnpack(PyObject *); /*proto*/

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from pytracer */


struct __pyx_obj_8pytracer__Linkable {
  PyObject_HEAD
  graphfile_linkable_t linkable;
};


struct __pyx_obj_8pytracer_Tracer {
  PyObject_HEAD
  struct __pyx_vtabstruct_8pytracer_Tracer *__pyx_vtab;
  graphfile_writer_t writer;
  PyObject *fileobj;
  PyObject *stack;
  pid_t tracer_pid;
};

struct __pyx_vtabstruct_8pytracer_Tracer {
  void ((*_trace_event)(struct __pyx_obj_8pytracer_Tracer *,PyObject *,int ,void (*)));
  PyObject *((*_encode)(struct __pyx_obj_8pytracer_Tracer *,PyObject *));
  PyObject *((*_write)(struct __pyx_obj_8pytracer_Tracer *,PyObject *));
};
static struct __pyx_vtabstruct_8pytracer_Tracer *__pyx_vtabptr_8pytracer_Tracer;

static PyTypeObject *__pyx_ptype_8pytracer__Linkable = 0;
static PyTypeObject *__pyx_ptype_8pytracer_Tracer = 0;
static void (*(__pyx_f_8pytracer_allocate(int ))); /*proto*/
static FILE (*(__pyx_f_8pytracer_get_file(PyObject *))); /*proto*/
static int (__pyx_f_8pytracer_callback(struct __pyx_obj_8pytracer_Tracer *,PyObject *,int ,void (*))); /*proto*/


/* Implementation of pytracer */


static PyObject *__pyx_n_dumps;
static PyObject *__pyx_n_Error;
static PyObject *__pyx_n_marshal;
static PyObject *__pyx_n_Exception;

static PyObject *__pyx_n_MemoryError;

static void (*__pyx_f_8pytracer_allocate(int __pyx_v_size)) {
  void (*__pyx_v_ptr);
  void (*__pyx_r);
  int __pyx_1;
  PyObject *__pyx_2 = 0;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":83 */
  __pyx_v_ptr = malloc(__pyx_v_size);

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":84 */
  __pyx_1 = (__pyx_v_ptr == NULL);
  if (__pyx_1) {

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":85 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_MemoryError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":86 */
  __pyx_r = __pyx_v_ptr;
  goto __pyx_L0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_WriteUnraisable("pytracer.allocate");
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_k4p;

static char (__pyx_k4[]) = "Invalid fileobj";

static FILE (*__pyx_f_8pytracer_get_file(PyObject *__pyx_v_fileobj)) {
  FILE (*__pyx_v_file);
  FILE (*__pyx_r);
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  Py_INCREF(__pyx_v_fileobj);

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":92 */
  __pyx_v_file = PyFile_AsFile(__pyx_v_fileobj);

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":93 */
  __pyx_1 = (NULL == __pyx_v_file);
  if (__pyx_1) {

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":94 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_Error); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
    Py_INCREF(__pyx_k4p);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k4p);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":95 */
  __pyx_r = __pyx_v_file;
  goto __pyx_L0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_WriteUnraisable("pytracer.get_file");
  __pyx_L0:;
  Py_DECREF(__pyx_v_fileobj);
  return __pyx_r;
}

static PyObject *__pyx_n_graphfile_writer_init;


static int __pyx_f_8pytracer_6Tracer___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_8pytracer_6Tracer___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_fileobj = 0;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"fileobj",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_fileobj)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_fileobj);

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":106 */
  __pyx_1 = (0 != graphfile_writer_init((&((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->writer),__pyx_f_8pytracer_get_file(__pyx_v_fileobj)));
  if (__pyx_1) {

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":107 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_Error); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
    Py_INCREF(__pyx_n_graphfile_writer_init);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_n_graphfile_writer_init);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":108 */
  Py_INCREF(__pyx_v_fileobj);
  Py_DECREF(((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->fileobj);
  ((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->fileobj = __pyx_v_fileobj;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":109 */
  Py_INCREF(Py_None);
  Py_DECREF(((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->stack);
  ((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->stack = Py_None;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("pytracer.Tracer.__new__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_fileobj);
  return __pyx_r;
}

static void __pyx_f_8pytracer_6Tracer___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_8pytracer_6Tracer___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":111 */
  graphfile_writer_fini((&((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->writer));

  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_n_gettimeofday;
static PyObject *__pyx_n_OSError;
static PyObject *__pyx_n_times;
static PyObject *__pyx_n_append;
static PyObject *__pyx_n_f_code;
static PyObject *__pyx_n_f_lineno;
static PyObject *__pyx_n_pop;
static PyObject *__pyx_n_co_filename;
static PyObject *__pyx_n_co_name;


static void __pyx_f_8pytracer_6Tracer__trace_event(struct __pyx_obj_8pytracer_Tracer *__pyx_v_self,PyObject *__pyx_v_frame,int __pyx_v_event,void (*__pyx_v_trace_arg)) {
  struct tms __pyx_v_times_result;
  clock_t __pyx_v_times_return;
  double __pyx_v_sys_time;
  double __pyx_v_user_time;
  unsigned PY_LONG_LONG __pyx_v_real_time;
  struct timeval __pyx_v_tv;
  PyObject *__pyx_v_errno;
  PyObject *__pyx_v_code;
  PyObject *__pyx_v_lineno;
  PyObject *__pyx_v_start_user_time;
  PyObject *__pyx_v_start_sys_time;
  PyObject *__pyx_v_start_real_time;
  PyObject *__pyx_v_children;
  PyObject *__pyx_v_child;
  PyObject *__pyx_v_parent_code;
  PyObject *__pyx_v_parent_times;
  PyObject *__pyx_v_parent_children;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_frame);
  __pyx_v_errno = Py_None; Py_INCREF(Py_None);
  __pyx_v_code = Py_None; Py_INCREF(Py_None);
  __pyx_v_lineno = Py_None; Py_INCREF(Py_None);
  __pyx_v_start_user_time = Py_None; Py_INCREF(Py_None);
  __pyx_v_start_sys_time = Py_None; Py_INCREF(Py_None);
  __pyx_v_start_real_time = Py_None; Py_INCREF(Py_None);
  __pyx_v_children = Py_None; Py_INCREF(Py_None);
  __pyx_v_child = Py_None; Py_INCREF(Py_None);
  __pyx_v_parent_code = Py_None; Py_INCREF(Py_None);
  __pyx_v_parent_times = Py_None; Py_INCREF(Py_None);
  __pyx_v_parent_children = Py_None; Py_INCREF(Py_None);

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":120 */
  __pyx_1 = (__pyx_v_self->tracer_pid != getpid());
  if (__pyx_1) {

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":123 */
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":125 */
  __pyx_1 = (__pyx_v_event != PyTrace_CALL);
  if (__pyx_1) {
    __pyx_1 = (__pyx_v_event != PyTrace_RETURN);
  }
  if (__pyx_1) {

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":126 */
    goto __pyx_L0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":127 */
  __pyx_1 = (0 != gettimeofday((&__pyx_v_tv),NULL));
  if (__pyx_1) {

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":128 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_Error); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
    Py_INCREF(__pyx_n_gettimeofday);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_n_gettimeofday);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":129 */
  __pyx_v_real_time = ((((unsigned PY_LONG_LONG )1000000) * __pyx_v_tv.tv_sec) + ((unsigned PY_LONG_LONG )__pyx_v_tv.tv_usec));

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":131 */
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  Py_DECREF(__pyx_v_errno);
  __pyx_v_errno = __pyx_2;
  __pyx_2 = 0;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":132 */
  __pyx_v_times_return = times((&__pyx_v_times_result));

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":133 */
  __pyx_1 = (__pyx_v_times_return == ((int )(-1)));
  if (__pyx_1) {

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":134 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_OSError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
    Py_INCREF(__pyx_v_errno);
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_errno);
    Py_INCREF(__pyx_n_times);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_n_times);
    __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":135 */
  __pyx_v_user_time = (((double )__pyx_v_times_result.tms_utime) / HZ);

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":136 */
  __pyx_v_sys_time = (((double )__pyx_v_times_result.tms_stime) / HZ);

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":137 */
  __pyx_1 = (__pyx_v_event == PyTrace_CALL);
  if (__pyx_1) {

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":138 */
    __pyx_3 = PyObject_GetAttr(__pyx_v_self->stack, __pyx_n_append); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
    __pyx_4 = PyObject_GetAttr(__pyx_v_frame, __pyx_n_f_code); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
    __pyx_2 = PyObject_GetAttr(__pyx_v_frame, __pyx_n_f_lineno); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_4);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_2);
    __pyx_4 = 0;
    __pyx_2 = 0;
    __pyx_4 = PyFloat_FromDouble(__pyx_v_user_time); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
    __pyx_2 = PyFloat_FromDouble(__pyx_v_sys_time); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
    __pyx_6 = PyLong_FromUnsignedLongLong(__pyx_v_real_time); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
    __pyx_7 = PyTuple_New(3); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_7, 0, __pyx_4);
    PyTuple_SET_ITEM(__pyx_7, 1, __pyx_2);
    PyTuple_SET_ITEM(__pyx_7, 2, __pyx_6);
    __pyx_4 = 0;
    __pyx_2 = 0;
    __pyx_6 = 0;
    __pyx_4 = PyList_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_5);
    PyTuple_SET_ITEM(__pyx_2, 1, __pyx_7);
    PyTuple_SET_ITEM(__pyx_2, 2, __pyx_4);
    __pyx_5 = 0;
    __pyx_7 = 0;
    __pyx_4 = 0;
    __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_6); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    goto __pyx_L6;
  }
  /*else*/ {

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":142 */
    __pyx_7 = PyObject_GetAttr(__pyx_v_self->stack, __pyx_n_pop); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    __pyx_4 = PyObject_CallObject(__pyx_7, 0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_2 = PyObject_GetIter(__pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_3 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    __pyx_6 = PyObject_GetIter(__pyx_3); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_5 = __Pyx_UnpackItem(__pyx_6); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_v_code);
    __pyx_v_code = __pyx_5;
    __pyx_5 = 0;
    __pyx_7 = __Pyx_UnpackItem(__pyx_6); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_v_lineno);
    __pyx_v_lineno = __pyx_7;
    __pyx_7 = 0;
    if (__Pyx_EndUnpack(__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_4 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    __pyx_3 = PyObject_GetIter(__pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_5 = __Pyx_UnpackItem(__pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_v_start_user_time);
    __pyx_v_start_user_time = __pyx_5;
    __pyx_5 = 0;
    __pyx_7 = __Pyx_UnpackItem(__pyx_3); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_v_start_sys_time);
    __pyx_v_start_sys_time = __pyx_7;
    __pyx_7 = 0;
    __pyx_6 = __Pyx_UnpackItem(__pyx_3); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_v_start_real_time);
    __pyx_v_start_real_time = __pyx_6;
    __pyx_6 = 0;
    if (__Pyx_EndUnpack(__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_4 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_v_children);
    __pyx_v_children = __pyx_4;
    __pyx_4 = 0;
    if (__Pyx_EndUnpack(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":143 */
    __pyx_5 = PyObject_GetAttr(__pyx_v_code, __pyx_n_co_filename); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}
    __pyx_7 = PyObject_GetAttr(__pyx_v_code, __pyx_n_co_name); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}
    __pyx_6 = PyTuple_New(3); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_5);
    PyTuple_SET_ITEM(__pyx_6, 1, __pyx_7);
    Py_INCREF(__pyx_v_lineno);
    PyTuple_SET_ITEM(__pyx_6, 2, __pyx_v_lineno);
    __pyx_5 = 0;
    __pyx_7 = 0;
    __pyx_3 = PyFloat_FromDouble(__pyx_v_user_time); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
    __pyx_4 = PyNumber_Subtract(__pyx_3, __pyx_v_start_user_time); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyFloat_FromDouble(__pyx_v_sys_time); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
    __pyx_5 = PyNumber_Subtract(__pyx_2, __pyx_v_start_sys_time); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_7 = PyLong_FromUnsignedLongLong(__pyx_v_real_time); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
    __pyx_3 = PyNumber_Subtract(__pyx_7, __pyx_v_start_real_time); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_2 = PyTuple_New(3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
    PyTuple_SET_ITEM(__pyx_2, 1, __pyx_5);
    PyTuple_SET_ITEM(__pyx_2, 2, __pyx_3);
    __pyx_4 = 0;
    __pyx_5 = 0;
    __pyx_3 = 0;
    __pyx_7 = PyTuple_New(2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_7, 0, __pyx_6);
    PyTuple_SET_ITEM(__pyx_7, 1, __pyx_2);
    __pyx_6 = 0;
    __pyx_2 = 0;
    __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_7);
    Py_INCREF(__pyx_v_children);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_v_children);
    __pyx_7 = 0;
    __pyx_5 = ((struct __pyx_vtabstruct_8pytracer_Tracer *)__pyx_v_self->__pyx_vtab)->_write(__pyx_v_self,__pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_v_child);
    __pyx_v_child = __pyx_5;
    __pyx_5 = 0;

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":147 */
    __pyx_3 = PyInt_FromLong((-1)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
    __pyx_6 = PyObject_GetItem(__pyx_v_self->stack, __pyx_3); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyObject_GetIter(__pyx_6); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_7 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
    Py_DECREF(__pyx_v_parent_code);
    __pyx_v_parent_code = __pyx_7;
    __pyx_7 = 0;
    __pyx_4 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
    Py_DECREF(__pyx_v_parent_times);
    __pyx_v_parent_times = __pyx_4;
    __pyx_4 = 0;
    __pyx_5 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
    Py_DECREF(__pyx_v_parent_children);
    __pyx_v_parent_children = __pyx_5;
    __pyx_5 = 0;
    if (__Pyx_EndUnpack(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":148 */
    __pyx_3 = PyObject_GetAttr(__pyx_v_parent_children, __pyx_n_append); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
    __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
    Py_INCREF(__pyx_v_child);
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_v_child);
    __pyx_7 = PyObject_CallObject(__pyx_3, __pyx_6); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_7); __pyx_7 = 0;
  }
  __pyx_L6:;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_WriteUnraisable("pytracer.Tracer._trace_event");
  __pyx_L0:;
  Py_DECREF(__pyx_v_errno);
  Py_DECREF(__pyx_v_code);
  Py_DECREF(__pyx_v_lineno);
  Py_DECREF(__pyx_v_start_user_time);
  Py_DECREF(__pyx_v_start_sys_time);
  Py_DECREF(__pyx_v_start_real_time);
  Py_DECREF(__pyx_v_children);
  Py_DECREF(__pyx_v_child);
  Py_DECREF(__pyx_v_parent_code);
  Py_DECREF(__pyx_v_parent_times);
  Py_DECREF(__pyx_v_parent_children);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_frame);
}

static PyObject *__pyx_f_8pytracer_6Tracer__encode(struct __pyx_obj_8pytracer_Tracer *__pyx_v_self,PyObject *__pyx_v_data) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_data);

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":151 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_dumps); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  Py_INCREF(__pyx_v_data);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_data);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("pytracer.Tracer._encode");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_data);
  return __pyx_r;
}

static PyObject *__pyx_n_len;
static PyObject *__pyx_n_enumerate;
static PyObject *__pyx_n_graphfile_writer_write;


static PyObject *__pyx_f_8pytracer_6Tracer__write(struct __pyx_obj_8pytracer_Tracer *__pyx_v_self,PyObject *__pyx_v_node) {
  PyObject *__pyx_v_data;
  PyObject *__pyx_v_linkables;
  PyObject *__pyx_v_databuf;
  struct __pyx_obj_8pytracer__Linkable *__pyx_v_result_linkable;
  char (*__pyx_v_buffer);
  Py_ssize_t __pyx_v_buffer_length;
  graphfile_linkable_t (*__pyx_v_c_linkables);
  graphfile_size_t __pyx_v_i;
  int __pyx_v_result;
  PyObject *__pyx_v_linkable;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  graphfile_size_t __pyx_6;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_node);
  __pyx_v_data = Py_None; Py_INCREF(Py_None);
  __pyx_v_linkables = Py_None; Py_INCREF(Py_None);
  __pyx_v_databuf = Py_None; Py_INCREF(Py_None);
  __pyx_v_result_linkable = ((struct __pyx_obj_8pytracer__Linkable *)Py_None); Py_INCREF(Py_None);
  __pyx_v_linkable = Py_None; Py_INCREF(Py_None);

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":154 */
  __pyx_1 = PyObject_GetIter(__pyx_v_node); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
  __pyx_2 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
  Py_DECREF(__pyx_v_data);
  __pyx_v_data = __pyx_2;
  __pyx_2 = 0;
  __pyx_2 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
  Py_DECREF(__pyx_v_linkables);
  __pyx_v_linkables = __pyx_2;
  __pyx_2 = 0;
  if (__Pyx_EndUnpack(__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":155 */
  __pyx_2 = ((struct __pyx_vtabstruct_8pytracer_Tracer *)__pyx_v_self->__pyx_vtab)->_encode(__pyx_v_self,__pyx_v_data); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
  Py_DECREF(__pyx_v_databuf);
  __pyx_v_databuf = __pyx_2;
  __pyx_2 = 0;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":163 */
  __pyx_3 = PyString_AsStringAndSize(__pyx_v_databuf,(&__pyx_v_buffer),(&__pyx_v_buffer_length)); if (__pyx_3 == (-1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":164 */
  __pyx_1 = PyInt_FromLong((sizeof(graphfile_linkable_t ))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
  Py_INCREF(__pyx_v_linkables);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_linkables);
  __pyx_5 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_2 = PyNumber_Multiply(__pyx_1, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_3 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_v_c_linkables = ((graphfile_linkable_t (*))__pyx_f_8pytracer_allocate(__pyx_3));

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":165 */
  /*try:*/ {

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":166 */
    __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_enumerate); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L3;}
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L3;}
    Py_INCREF(__pyx_v_linkables);
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_linkables);
    __pyx_5 = PyObject_CallObject(__pyx_4, __pyx_1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L3;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_2 = PyObject_GetIter(__pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L3;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    for (;;) {
      __pyx_4 = PyIter_Next(__pyx_2);
      if (!__pyx_4) {
        if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L3;}
        break;
      }
      __pyx_1 = PyObject_GetIter(__pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L3;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_5 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L3;}
      __pyx_6 = PyInt_AsUnsignedLongLongMask(__pyx_5); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L3;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_v_i = __pyx_6;
      __pyx_4 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L3;}
      Py_DECREF(__pyx_v_linkable);
      __pyx_v_linkable = __pyx_4;
      __pyx_4 = 0;
      if (__Pyx_EndUnpack(__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L3;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;

      /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":167 */
      (__pyx_v_c_linkables[__pyx_v_i]) = ((struct __pyx_obj_8pytracer__Linkable *)__pyx_v_linkable)->linkable;
    }
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":168 */
    __pyx_5 = PyObject_CallObject(((PyObject*)__pyx_ptype_8pytracer__Linkable), 0); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 168; goto __pyx_L3;}
    if (!__Pyx_TypeTest(__pyx_5, __pyx_ptype_8pytracer__Linkable)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 168; goto __pyx_L3;}
    Py_DECREF(((PyObject *)__pyx_v_result_linkable));
    __pyx_v_result_linkable = ((struct __pyx_obj_8pytracer__Linkable *)__pyx_5);
    __pyx_5 = 0;

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":169 */
    __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; goto __pyx_L3;}
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; goto __pyx_L3;}
    Py_INCREF(__pyx_v_linkables);
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_linkables);
    __pyx_2 = PyObject_CallObject(__pyx_4, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; goto __pyx_L3;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_6 = PyInt_AsUnsignedLongLongMask(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; goto __pyx_L3;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_v_result = graphfile_writer_write((&__pyx_v_self->writer),__pyx_v_buffer,__pyx_v_buffer_length,__pyx_v_c_linkables,__pyx_6,(&__pyx_v_result_linkable->linkable));

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":172 */
    __pyx_3 = (__pyx_v_result != 0);
    if (__pyx_3) {

      /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":173 */
      __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_Error); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L3;}
      __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L3;}
      Py_INCREF(__pyx_n_graphfile_writer_write);
      PyTuple_SET_ITEM(__pyx_4, 0, __pyx_n_graphfile_writer_write);
      __pyx_1 = PyObject_CallObject(__pyx_5, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L3;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __Pyx_Raise(__pyx_1, 0, 0);
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L3;}
      goto __pyx_L7;
    }
    __pyx_L7:;

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":174 */
    Py_INCREF(((PyObject *)__pyx_v_result_linkable));
    __pyx_r = ((PyObject *)__pyx_v_result_linkable);
    goto __pyx_L2;
  }
  /*finally:*/ {
    int __pyx_why;
    __pyx_why = 0; goto __pyx_L4;
    __pyx_L2: __pyx_why = 3; goto __pyx_L4;
    __pyx_L3: {
      __pyx_why = 4;
      Py_XDECREF(__pyx_2); __pyx_2 = 0;
      Py_XDECREF(__pyx_5); __pyx_5 = 0;
      Py_XDECREF(__pyx_4); __pyx_4 = 0;
      Py_XDECREF(__pyx_1); __pyx_1 = 0;
      PyErr_Fetch(&__pyx_2, &__pyx_5, &__pyx_4);
      __pyx_3 = __pyx_lineno;
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":176 */
    free(__pyx_v_c_linkables);
    switch (__pyx_why) {
      case 3: goto __pyx_L0;
      case 4: {
        PyErr_Restore(__pyx_2, __pyx_5, __pyx_4);
        __pyx_lineno = __pyx_3;
        __pyx_2 = 0;
        __pyx_5 = 0;
        __pyx_4 = 0;
        goto __pyx_L1;
      }
    }
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("pytracer.Tracer._write");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_data);
  Py_DECREF(__pyx_v_linkables);
  Py_DECREF(__pyx_v_databuf);
  Py_DECREF(__pyx_v_result_linkable);
  Py_DECREF(__pyx_v_linkable);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_node);
  return __pyx_r;
}

static PyObject *__pyx_n_graphfile_writer_set_root;

static PyObject *__pyx_k9p;

static char (__pyx_k9[]) = "Cannot create a nested trace";

static PyObject *__pyx_f_8pytracer_6Tracer_trace(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8pytracer_6Tracer_trace(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_func = 0;
  struct __pyx_obj_8pytracer__Linkable *__pyx_v_root;
  PyObject *__pyx_v_code;
  PyObject *__pyx_v_times;
  PyObject *__pyx_v_children;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  static char *__pyx_argnames[] = {"func",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_func)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_func);
  __pyx_v_root = ((struct __pyx_obj_8pytracer__Linkable *)Py_None); Py_INCREF(Py_None);
  __pyx_v_code = Py_None; Py_INCREF(Py_None);
  __pyx_v_times = Py_None; Py_INCREF(Py_None);
  __pyx_v_children = Py_None; Py_INCREF(Py_None);

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":180 */
  __pyx_1 = ((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->stack == Py_None;
  if (!__pyx_1) {
    PyErr_SetObject(PyExc_AssertionError, __pyx_k9p);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 180; goto __pyx_L1;}
  }

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":181 */
  ((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->tracer_pid = getpid();

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":182 */
  __pyx_2 = PyList_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(3); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  Py_INCREF(Py_None);
  PyTuple_SET_ITEM(__pyx_3, 0, Py_None);
  Py_INCREF(Py_None);
  PyTuple_SET_ITEM(__pyx_3, 1, Py_None);
  PyTuple_SET_ITEM(__pyx_3, 2, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyList_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  PyList_SET_ITEM(__pyx_2, 0, __pyx_3);
  __pyx_3 = 0;
  Py_DECREF(((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->stack);
  ((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->stack = __pyx_2;
  __pyx_2 = 0;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":183 */
  PyEval_SetProfile(((void (*))(&__pyx_f_8pytracer_callback)),__pyx_v_self);

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":184 */
  /*try:*/ {

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":185 */
    __pyx_3 = PyObject_CallObject(__pyx_v_func, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 185; goto __pyx_L3;}
    __pyx_r = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L2;
  }
  /*finally:*/ {
    int __pyx_why;
    __pyx_why = 0; goto __pyx_L4;
    __pyx_L2: __pyx_why = 3; goto __pyx_L4;
    __pyx_L3: {
      __pyx_why = 4;
      Py_XDECREF(__pyx_2); __pyx_2 = 0;
      Py_XDECREF(__pyx_3); __pyx_3 = 0;
      PyErr_Fetch(&__pyx_2, &__pyx_3, &__pyx_4);
      __pyx_1 = __pyx_lineno;
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":187 */
    __pyx_5 = (((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->tracer_pid == getpid());
    if (__pyx_5) {

      /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":188 */
      PyEval_SetProfile(NULL,Py_None);

      /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":189 */
      __pyx_6 = PyObject_GetAttr(((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->stack, __pyx_n_pop); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 189; goto __pyx_L1;}
      __pyx_7 = PyObject_CallObject(__pyx_6, 0); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 189; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      __pyx_6 = PyObject_GetIter(__pyx_7); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 189; goto __pyx_L1;}
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      __pyx_7 = __Pyx_UnpackItem(__pyx_6); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 189; goto __pyx_L1;}
      Py_DECREF(__pyx_v_code);
      __pyx_v_code = __pyx_7;
      __pyx_7 = 0;
      __pyx_7 = __Pyx_UnpackItem(__pyx_6); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 189; goto __pyx_L1;}
      Py_DECREF(__pyx_v_times);
      __pyx_v_times = __pyx_7;
      __pyx_7 = 0;
      __pyx_7 = __Pyx_UnpackItem(__pyx_6); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 189; goto __pyx_L1;}
      Py_DECREF(__pyx_v_children);
      __pyx_v_children = __pyx_7;
      __pyx_7 = 0;
      if (__Pyx_EndUnpack(__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 189; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;

      /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":190 */
      __pyx_5 = PyObject_IsTrue(((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->stack); if (__pyx_5 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
      if (!(!__pyx_5)) {
        PyErr_SetNone(PyExc_AssertionError);
        {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
      }

      /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":191 */
      Py_INCREF(Py_None);
      Py_DECREF(((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->stack);
      ((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->stack = Py_None;

      /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":192 */
      ((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->tracer_pid = (-1);

      /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":193 */
      __pyx_7 = PyTuple_New(2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
      Py_INCREF(Py_None);
      PyTuple_SET_ITEM(__pyx_7, 0, Py_None);
      Py_INCREF(__pyx_v_children);
      PyTuple_SET_ITEM(__pyx_7, 1, __pyx_v_children);
      __pyx_6 = ((struct __pyx_vtabstruct_8pytracer_Tracer *)((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->__pyx_vtab)->_write(((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self),__pyx_7); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      if (!__Pyx_TypeTest(__pyx_6, __pyx_ptype_8pytracer__Linkable)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
      Py_DECREF(((PyObject *)__pyx_v_root));
      __pyx_v_root = ((struct __pyx_obj_8pytracer__Linkable *)__pyx_6);
      __pyx_6 = 0;

      /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":194 */
      __pyx_5 = (0 != graphfile_writer_set_root((&((struct __pyx_obj_8pytracer_Tracer *)__pyx_v_self)->writer),(&__pyx_v_root->linkable)));
      if (__pyx_5) {

        /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":195 */
        __pyx_7 = __Pyx_GetName(__pyx_m, __pyx_n_Error); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 195; goto __pyx_L1;}
        __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 195; goto __pyx_L1;}
        Py_INCREF(__pyx_n_graphfile_writer_set_root);
        PyTuple_SET_ITEM(__pyx_6, 0, __pyx_n_graphfile_writer_set_root);
        __pyx_8 = PyObject_CallObject(__pyx_7, __pyx_6); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 195; goto __pyx_L1;}
        Py_DECREF(__pyx_7); __pyx_7 = 0;
        Py_DECREF(__pyx_6); __pyx_6 = 0;
        __Pyx_Raise(__pyx_8, 0, 0);
        Py_DECREF(__pyx_8); __pyx_8 = 0;
        {__pyx_filename = __pyx_f[0]; __pyx_lineno = 195; goto __pyx_L1;}
        goto __pyx_L6;
      }
      __pyx_L6:;
      goto __pyx_L5;
    }
    __pyx_L5:;
    switch (__pyx_why) {
      case 3: goto __pyx_L0;
      case 4: {
        PyErr_Restore(__pyx_2, __pyx_3, __pyx_4);
        __pyx_lineno = __pyx_1;
        __pyx_2 = 0;
        __pyx_3 = 0;
        __pyx_4 = 0;
        goto __pyx_L1;
      }
    }
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  __Pyx_AddTraceback("pytracer.Tracer.trace");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_root);
  Py_DECREF(__pyx_v_code);
  Py_DECREF(__pyx_v_times);
  Py_DECREF(__pyx_v_children);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_func);
  return __pyx_r;
}

static int __pyx_f_8pytracer_callback(struct __pyx_obj_8pytracer_Tracer *__pyx_v_tracer,PyObject *__pyx_v_frame,int __pyx_v_event,void (*__pyx_v_trace_arg)) {
  int __pyx_r;
  Py_INCREF(__pyx_v_tracer);
  Py_INCREF(__pyx_v_frame);

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":198 */
  ((struct __pyx_vtabstruct_8pytracer_Tracer *)__pyx_v_tracer->__pyx_vtab)->_trace_event(__pyx_v_tracer,__pyx_v_frame,__pyx_v_event,__pyx_v_trace_arg);

  __pyx_r = 0;
  Py_DECREF(__pyx_v_tracer);
  Py_DECREF(__pyx_v_frame);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_Error, "Error"},
  {&__pyx_n_Exception, "Exception"},
  {&__pyx_n_MemoryError, "MemoryError"},
  {&__pyx_n_OSError, "OSError"},
  {&__pyx_n_append, "append"},
  {&__pyx_n_co_filename, "co_filename"},
  {&__pyx_n_co_name, "co_name"},
  {&__pyx_n_dumps, "dumps"},
  {&__pyx_n_enumerate, "enumerate"},
  {&__pyx_n_f_code, "f_code"},
  {&__pyx_n_f_lineno, "f_lineno"},
  {&__pyx_n_gettimeofday, "gettimeofday"},
  {&__pyx_n_graphfile_writer_init, "graphfile_writer_init"},
  {&__pyx_n_graphfile_writer_set_root, "graphfile_writer_set_root"},
  {&__pyx_n_graphfile_writer_write, "graphfile_writer_write"},
  {&__pyx_n_len, "len"},
  {&__pyx_n_marshal, "marshal"},
  {&__pyx_n_pop, "pop"},
  {&__pyx_n_times, "times"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k4p, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k9p, __pyx_k9, sizeof(__pyx_k9)},
  {0, 0, 0}
};

static PyObject *__pyx_tp_new_8pytracer__Linkable(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  return o;
}

static void __pyx_tp_dealloc_8pytracer__Linkable(PyObject *o) {
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_8pytracer__Linkable(PyObject *o, visitproc v, void *a) {
  return 0;
}

static int __pyx_tp_clear_8pytracer__Linkable(PyObject *o) {
  return 0;
}

static struct PyMethodDef __pyx_methods_8pytracer__Linkable[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number__Linkable = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence__Linkable = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping__Linkable = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer__Linkable = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_8pytracer__Linkable = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "pytracer._Linkable", /*tp_name*/
  sizeof(struct __pyx_obj_8pytracer__Linkable), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_8pytracer__Linkable, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number__Linkable, /*tp_as_number*/
  &__pyx_tp_as_sequence__Linkable, /*tp_as_sequence*/
  &__pyx_tp_as_mapping__Linkable, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer__Linkable, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_8pytracer__Linkable, /*tp_traverse*/
  __pyx_tp_clear_8pytracer__Linkable, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_8pytracer__Linkable, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_8pytracer__Linkable, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};
static struct __pyx_vtabstruct_8pytracer_Tracer __pyx_vtable_8pytracer_Tracer;

static PyObject *__pyx_tp_new_8pytracer_Tracer(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_8pytracer_Tracer *p = (struct __pyx_obj_8pytracer_Tracer *)o;
  *(struct __pyx_vtabstruct_8pytracer_Tracer **)&p->__pyx_vtab = __pyx_vtabptr_8pytracer_Tracer;
  p->fileobj = Py_None; Py_INCREF(Py_None);
  p->stack = Py_None; Py_INCREF(Py_None);
  if (__pyx_f_8pytracer_6Tracer___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_8pytracer_Tracer(PyObject *o) {
  struct __pyx_obj_8pytracer_Tracer *p = (struct __pyx_obj_8pytracer_Tracer *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_8pytracer_6Tracer___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  Py_XDECREF(p->fileobj);
  Py_XDECREF(p->stack);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_8pytracer_Tracer(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_8pytracer_Tracer *p = (struct __pyx_obj_8pytracer_Tracer *)o;
  if (p->fileobj) {
    e = (*v)(p->fileobj, a); if (e) return e;
  }
  if (p->stack) {
    e = (*v)(p->stack, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_8pytracer_Tracer(PyObject *o) {
  struct __pyx_obj_8pytracer_Tracer *p = (struct __pyx_obj_8pytracer_Tracer *)o;
  Py_XDECREF(p->fileobj);
  p->fileobj = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(p->stack);
  p->stack = Py_None; Py_INCREF(Py_None);
  return 0;
}

static struct PyMethodDef __pyx_methods_8pytracer_Tracer[] = {
  {"trace", (PyCFunction)__pyx_f_8pytracer_6Tracer_trace, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_8pytracer_Tracer[] = {
  {"fileobj", T_OBJECT, offsetof(struct __pyx_obj_8pytracer_Tracer, fileobj), READONLY, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Tracer = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Tracer = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Tracer = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Tracer = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_8pytracer_Tracer = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "pytracer.Tracer", /*tp_name*/
  sizeof(struct __pyx_obj_8pytracer_Tracer), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_8pytracer_Tracer, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Tracer, /*tp_as_number*/
  &__pyx_tp_as_sequence_Tracer, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Tracer, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Tracer, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_8pytracer_Tracer, /*tp_traverse*/
  __pyx_tp_clear_8pytracer_Tracer, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_8pytracer_Tracer, /*tp_methods*/
  __pyx_members_8pytracer_Tracer, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_8pytracer_Tracer, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initpytracer(void); /*proto*/
PyMODINIT_FUNC initpytracer(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("pytracer", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_8pytracer__Linkable) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "_Linkable", (PyObject *)&__pyx_type_8pytracer__Linkable) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  __pyx_ptype_8pytracer__Linkable = &__pyx_type_8pytracer__Linkable;
  __pyx_vtabptr_8pytracer_Tracer = &__pyx_vtable_8pytracer_Tracer;
  *(void(**)())&__pyx_vtable_8pytracer_Tracer._trace_event = (void(*)())__pyx_f_8pytracer_6Tracer__trace_event;
  *(void(**)())&__pyx_vtable_8pytracer_Tracer._encode = (void(*)())__pyx_f_8pytracer_6Tracer__encode;
  *(void(**)())&__pyx_vtable_8pytracer_Tracer._write = (void(*)())__pyx_f_8pytracer_6Tracer__write;
  __pyx_type_8pytracer_Tracer.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_8pytracer_Tracer) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_8pytracer_Tracer.tp_dict, __pyx_vtabptr_8pytracer_Tracer) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Tracer", (PyObject *)&__pyx_type_8pytracer_Tracer) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  __pyx_ptype_8pytracer_Tracer = &__pyx_type_8pytracer_Tracer;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":1 */
  __pyx_1 = PyList_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_INCREF(__pyx_n_dumps);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_dumps);
  __pyx_2 = __Pyx_Import(__pyx_n_marshal, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_dumps); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_dumps, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":88 */
  __pyx_2 = PyDict_New(); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_Exception); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = __Pyx_CreateClass(__pyx_3, __pyx_2, __pyx_n_Error, "pytracer"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_Error, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/a/home/eyal/eyal_tools/tracer/pytracer.pyx":197 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("pytracer");
}

static char *__pyx_filenames[] = {
  "pytracer.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type)) {
        if (PyErr_Warn(PyExc_DeprecationWarning,
                "raising a string exception is deprecated"))
            goto raise_error;
    }
    else if (PyType_Check(type) || PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        if (PyInstance_Check(type))
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
        else
            type = (PyObject*) type->ob_type;
        Py_INCREF(type);
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static void __Pyx_UnpackError(void) {
    PyErr_SetString(PyExc_ValueError, "unpack sequence of wrong size");
}

static PyObject *__Pyx_UnpackItem(PyObject *iter) {
    PyObject *item;
    if (!(item = PyIter_Next(iter))) {
        if (!PyErr_Occurred())
            __Pyx_UnpackError();
    }
    return item;
}

static int __Pyx_EndUnpack(PyObject *iter) {
    PyObject *item;
    if ((item = PyIter_Next(iter))) {
        Py_DECREF(item);
        __Pyx_UnpackError();
        return -1;
    }
    else if (!PyErr_Occurred())
        return 0;
    else
        return -1;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
